name: "Romil Kulshreshtha's Blog"
favicon: null
layout_spectrum: 0.9917893237434328
typography_spectrum: 0.89409
title: where I explore my own ideas and dreams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2c3b58'
    - '#99b4d1'
    - '#0001d8'
    - '#b1257e'
  brandStrength: 0.2612130520865321
  lightness: 0.1077444814145565
  saturation: 0.8480595306027681
  rhythmicContrast: 0.5021130300592631
purpose: []
